# Generated by Django 5.2.9 on 2025-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprofile',
            name='flutterwave_subaccount_id',
        ),
    ]
