# Generated by Django 5.2.9 on 2025-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
