# Generated by Django 5.2.9 on 2025-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_country_user_gender_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerrequest',
            name='documents_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
