# Generated by Django 5.2.9 on 2025-12-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ownerrequest_documents_url_user_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerrequest',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
