# Generated by Django 5.2.9 on 2025-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_ownerrequest_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerrequest',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='ownerrequest',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='id_type',
            field=models.CharField(choices=[('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('VOTERS_CARD', "Voter's Card")], default='NATIONAL_ID', max_length=20),
        ),
        migrations.AddField(
            model_name='ownerrequest',
            name='reason',
            field=models.TextField(default='', help_text='Reason for requesting owner status'),
        ),
    ]
