# Generated by Django (Manually)

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("properties", "Category")
    categories = [
        {"name": "House", "slug": "house"},
        {"name": "Shop", "slug": "shop"},
        {"name": "Land", "slug": "land"},
        {"name": "Apartment", "slug": "apartment"},
    ]
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data["name"], defaults={"slug": category_data["slug"]}
        )


def remove_categories(apps, schema_editor):
    Category = apps.get_model("properties", "Category")
    Category.objects.filter(name__in=["House", "Shop", "Land", "Apartment"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
