# Generated by Django 5.2.9 on 2025-12-26 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenity_property_average_rating_property_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('BANNED', 'Banned')], db_index=True, default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'category'], name='properties__status_9e4ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'property_type'], name='properties__status_e02930_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
    ]
