# Generated by Django 5.2.9 on 2025-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('HOUSE', 'House'), ('SHOP', 'Shop'), ('LAND', 'Land'), ('APARTMENT', 'Apartment')], default='HOUSE', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
