# Generated by Django 5.2.9 on 2025-12-27 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'price'], name='properties__status_800e45_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'category', 'price'], name='properties__status_65ccee_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'price'], name='properties__propert_19fbac_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_banned', 'status'], name='properties__is_bann_d064f2_idx'),
        ),
    ]
