# Generated by Django 5.2.9 on 2025-12-27 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
