# Generated by Django 5.2.9 on 2025-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_sync_legacy_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
